"""Add default_weight_kg to exercises

Revision ID: 17e08f32e371
Revises: e2011a23d1ec
Create Date: 2026-02-22 14:47:18.294885

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '17e08f32e371'
down_revision: Union[str, None] = 'e2011a23d1ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('default_weight_kg', sa.Float(), nullable=True))
    op.add_column('exercises', sa.Column('name_translations', sa.JSON(), nullable=True))
    op.add_column('routines', sa.Column('is_favorite', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('routines', 'is_favorite')
    op.drop_column('exercises', 'name_translations')
    op.drop_column('exercises', 'default_weight_kg')
    # ### end Alembic commands ###
