"""Add UserPreference

Revision ID: 3d397d0411ce
Revises: 79338cd692f5
Create Date: 2026-03-11 14:58:09.192235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d397d0411ce'
down_revision: Union[str, None] = '79338cd692f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_preferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('primary_goal', sa.String(), nullable=True),
    sa.Column('split_preference', sa.String(), nullable=True),
    sa.Column('strength_logic', sa.String(), nullable=True),
    sa.Column('cardio_preference', sa.String(), nullable=True),
    sa.Column('experience_level', sa.String(), nullable=True),
    sa.Column('available_equipment', sa.JSON(), nullable=True),
    sa.Column('training_days', sa.Integer(), nullable=True),
    sa.Column('session_duration', sa.String(), nullable=True),
    sa.Column('sleep_quality', sa.String(), nullable=True),
    sa.Column('active_job', sa.String(), nullable=True),
    sa.Column('progression_pace', sa.String(), nullable=True),
    sa.Column('has_injuries', sa.String(), nullable=True),
    sa.Column('injured_areas', sa.JSON(), nullable=True),
    sa.Column('other_information', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_quests_id'), 'quests', ['id'], unique=False)
    op.create_index(op.f('ix_user_quests_id'), 'user_quests', ['id'], unique=False)
    op.alter_column('users', 'level',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('1'))
    op.alter_column('users', 'experience',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'currency',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'currency',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'experience',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('users', 'level',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('1'))
    op.drop_index(op.f('ix_user_quests_id'), table_name='user_quests')
    op.drop_index(op.f('ix_quests_id'), table_name='quests')
    op.drop_table('user_preferences')
    # ### end Alembic commands ###
