"""add_context_level_to_user_preferences

Revision ID: 67fc3b0b1f0e
Revises: dd442d7410ab
Create Date: 2026-03-21 11:33:08.817033

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67fc3b0b1f0e'
down_revision: Union[str, None] = 'dd442d7410ab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_preferences', sa.Column('context_level', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_preferences', 'context_level')
    # ### end Alembic commands ###
