"""add secondary muscle

Revision ID: 8be5b321bffd
Revises: 17e08f32e371
Create Date: 2026-02-22 16:56:15.828953

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8be5b321bffd'
down_revision: Union[str, None] = '17e08f32e371'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('secondary_muscle', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('exercises', 'secondary_muscle')
    # ### end Alembic commands ###
