"""add_bodyweight_kg_to_session

Revision ID: 8e84873450a1
Revises: 3d397d0411ce
Create Date: 2026-03-11 17:34:46.495952

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8e84873450a1'
down_revision: Union[str, None] = '3d397d0411ce'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('bodyweight_kg', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'bodyweight_kg')
    # ### end Alembic commands ###
