"""add_locked_exercises_to_sessions

Revision ID: 959865bd035b
Revises: 8be5b321bffd
Create Date: 2026-03-01 15:12:41.498262

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '959865bd035b'
down_revision: Union[str, None] = '8be5b321bffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('locked_exercises', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'locked_exercises')
    # ### end Alembic commands ###
