"""add exercise difficulty and user demo fields

Revision ID: c5592eab8cac
Revises: d6e122325666
Create Date: 2026-03-08 14:30:26.768103

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5592eab8cac'
down_revision: Union[str, None] = 'd6e122325666'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('difficulty_factor', sa.Float(), server_default='1.0', nullable=False))
    op.add_column('exercises', sa.Column('bw_ratio', sa.Float(), nullable=True))
    op.add_column('users', sa.Column('is_demo', sa.Boolean(), server_default='false', nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'gender')
    op.drop_column('users', 'is_demo')
    op.drop_column('exercises', 'bw_ratio')
    op.drop_column('exercises', 'difficulty_factor')
    # ### end Alembic commands ###
