"""add_is_weekly_week_group_to_quests

Revision ID: de84f35a5913
Revises: a2f3b4c5d6e7
Create Date: 2026-03-15 20:31:47.187969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de84f35a5913'
down_revision: Union[str, None] = 'a2f3b4c5d6e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('quests', sa.Column('is_weekly', sa.Boolean(), nullable=True))
    op.add_column('quests', sa.Column('week_group', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('quests', 'week_group')
    op.drop_column('quests', 'is_weekly')
    # ### end Alembic commands ###
