"""Add user profile and exercise bodyweight flag

Revision ID: e2011a23d1ec
Revises: eab42601dc9e
Create Date: 2026-02-14 15:41:32.078732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e2011a23d1ec'
down_revision: Union[str, None] = 'eab42601dc9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('is_bodyweight', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('age', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('priorities', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'priorities')
    op.drop_column('users', 'age')
    op.drop_column('users', 'height')
    op.drop_column('users', 'weight')
    op.drop_column('exercises', 'is_bodyweight')
    # ### end Alembic commands ###
